[DSBL-83] Progress Indicators (Circular | Linear)
EYLatamSouth/beyondstyle pull request #23
Opened 2020-09-17 20:32 UTC by brubriele

## Componentes Controls

Importa **Circular Progress** e **Linear Progress** em formato default (indeterminate) a partir da [biblioteca material UI](https://material-ui.com/components/switches/),  implementa variações de estilo e cores previstas para bilbioteca _[Beyond Style](https://www.npmjs.com/package/beyondstyle)_ e agrupa componentes em page `ProgressIndicators.js`.

## Capturas de Tela
![feat-DSBL-83-progress-indicators](https://user-images.githubusercontent.com/42470334/93524765-5f79dd80-f90b-11ea-8ca4-362745acf23b.gif)

## Issue do JIRA
[DSBL-83](https://beyondlabs.atlassian.net/jira/software/projects/DSBL/boards/30?selectedIssue=DSBL-83)

## Wireframe
[Figma](https://www.figma.com/file/b3cNJXnD1N0wEpEzzgx1g8/BeyondLabs-Design-Kit)

2020-09-17 20:56 UTC, mocariz requested changes

2020-09-17 20:56 UTC, mocariz commented on src/lib/LinearProgress.js/index.js
> +const useStyles = makeStyles((theme) => ({
está apenas faltando sobrescrever a cor mais clara da barra para a mesma indicada no figma

2020-09-18 12:27 UTC, brubriele commented on src/lib/LinearProgress.js/index.js
> +const useStyles = makeStyles((theme) => ({
correção aplicada

2020-09-18 13:12 UTC, mocariz approved these changes

2020-09-18 13:13 UTC, merged